"""Add post image field

Revision ID: 128d0fb21de3
Revises: f79a4fcc79ce
Create Date: 2025-11-10 15:36:23.963102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128d0fb21de3'
down_revision = 'f79a4fcc79ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
