"""Add followers

Revision ID: 448423b11361
Revises: 713b9ef57ae3
Create Date: 2025-11-10 18:30:09.067894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448423b11361'
down_revision = '713b9ef57ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
